In [ ]:
!git clone https://github.com/PhonePe/pulse.git

In [23]:
import os
os.listdir("pulse")

['.git', 'data', 'LICENSE', 'README.md']

In [24]:
os.listdir("pulse/data")

['aggregated', 'map', 'top']

In [25]:
import json

path = "pulse/data/aggregated/transaction/country/india/state/delhi/2026/2.json"

with open(path, "r") as f:
    data = json.load(f)

data

{'success': True,
 'code': 'SUCCESS',
 'data': {'transactionData': [{'name': 'P2P',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 306838191,
      'amount': 788970305372.6831}]},
   {'name': 'Retail',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 802878308,
      'amount': 297272270584.85706}]},
   {'name': 'Utility',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 62188327,
      'amount': 90318390519.361}]}]},
 'responseTimestamp': 1785265809520}

In [26]:
data.keys()

dict_keys(['success', 'code', 'data', 'responseTimestamp'])

In [27]:
data["data"].keys()

dict_keys(['transactionData'])

In [28]:
data["data"]["transactionData"]

[{'name': 'P2P',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 306838191,
    'amount': 788970305372.6831}]},
 {'name': 'Retail',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 802878308,
    'amount': 297272270584.85706}]},
 {'name': 'Utility',
  'paymentInstruments': [{'type': 'TOTAL',
    'count': 62188327,
    'amount': 90318390519.361}]}]

In [29]:
import pandas as pd

rows = []

for item in data["data"]["transactionData"]:
    rows.append({
        "category": item["name"],
        "count": item["paymentInstruments"][0]["count"],
        "amount": item["paymentInstruments"][0]["amount"]
    })

df = pd.DataFrame(rows)

df.head(10)

  category      count        amount
0      P2P  306838191  7.889703e+11
1   Retail  802878308  2.972723e+11
2  Utility   62188327  9.031839e+10

In [30]:
rows = []

state = "delhi"
year = 2026
quarter = 2

for item in data["data"]["transactionData"]:
    rows.append({
        "state": state,
        "year": year,
        "quarter": quarter,
        "category": item["name"],
        "count": item["paymentInstruments"][0]["count"],
        "amount": item["paymentInstruments"][0]["amount"]
    })

df = pd.DataFrame(rows)

df

   state  year  quarter category      count        amount
0  delhi  2026        2      P2P  306838191  7.889703e+11
1  delhi  2026        2   Retail  802878308  2.972723e+11
2  delhi  2026        2  Utility   62188327  9.031839e+10

In [31]:
import os
import json
import pandas as pd

base_path = "pulse/data/aggregated/transaction/country/india/state"

rows = []

for state in os.listdir(base_path):

    state_path = os.path.join(base_path, state)

    for year in os.listdir(state_path):

        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):

            if file.endswith(".json"):

                quarter = file.replace(".json", "")
                file_path = os.path.join(year_path, file)

                with open(file_path, "r") as f:
                    data = json.load(f)

                for item in data["data"]["transactionData"]:

                    rows.append({
                        "state": state,
                        "year": int(year),
                        "quarter": int(quarter),
                        "category": item["name"],
                        "count": item["paymentInstruments"][0]["count"],
                        "amount": item["paymentInstruments"][0]["amount"]
                    })

transactions_df = pd.DataFrame(rows)

In [32]:
transactions_df.head()

                       state  year  quarter category  count        amount
0  andaman-&-nicobar-islands  2018        1      P2P   2297  1.551346e+07
1  andaman-&-nicobar-islands  2018        1   Retail   6656  1.848410e+06
2  andaman-&-nicobar-islands  2018        1  Utility    136  1.207260e+06
3  andaman-&-nicobar-islands  2018        2      P2P   4383  3.074418e+07
4  andaman-&-nicobar-islands  2018        2   Retail  10462  3.511613e+06

In [33]:
transactions_df.shape

(3671, 6)

In [34]:
transactions_df["category"].unique()

<StringArray>
['P2P', 'Retail', 'Utility']
Length: 3, dtype: str

In [35]:
transactions_df["year"].min(), transactions_df["year"].max()

(np.int64(2018), np.int64(2026))

In [36]:
transactions_df["state"].nunique()

36

In [37]:
transactions_df.duplicated(
    subset=["state", "year", "quarter", "category"]
).sum()

np.int64(0)

In [38]:
path = "pulse/data/aggregated/user/country/india/state/delhi/2026/2.json"

with open(path, "r") as f:
    user_data = json.load(f)

user_data

{'success': True,
 'code': 'SUCCESS',
 'data': {'aggregated': {'registeredCount': 21250201}},
 'responseTimestamp': 1785039928721}

In [39]:
user_data["data"]

{'aggregated': {'registeredCount': 21250201}}

In [40]:
base_path = "pulse/data/aggregated/user/country/india/state"

rows = []

for state in os.listdir(base_path):
    state_path = os.path.join(base_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):

                quarter = file.replace(".json", "")
                file_path = os.path.join(year_path, file)

                with open(file_path, "r") as f:
                    data = json.load(f)

                rows.append({
                    "state": state,
                    "year": int(year),
                    "quarter": int(quarter),
                    "registered_users": data["data"]["aggregated"]["registeredCount"]
                })

users_df = pd.DataFrame(rows)

In [41]:
users_df.head()

                       state  year  quarter  registered_users
0  andaman-&-nicobar-islands  2018        1              9292
1  andaman-&-nicobar-islands  2018        2             12739
2  andaman-&-nicobar-islands  2018        3             15949
3  andaman-&-nicobar-islands  2018        4             20050
4  andaman-&-nicobar-islands  2019        1             24369

In [42]:
users_df.shape

(1224, 4)

In [43]:
base_path = "pulse/data/aggregated/merchant/country/india/state"

rows = []

for state in os.listdir(base_path):
    state_path = os.path.join(base_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            if file.endswith(".json"):

                quarter = file.replace(".json", "")
                file_path = os.path.join(year_path, file)

                with open(file_path, "r") as f:
                    data = json.load(f)

                rows.append({
                    "state": state,
                    "year": int(year),
                    "quarter": int(quarter),
                    "registered_merchants": data["data"]["aggregated"]["registeredCount"]
                })

merchants_df = pd.DataFrame(rows)

In [44]:
merchants_df.head()

                       state  year  quarter  registered_merchants
0  andaman-&-nicobar-islands  2019        1                     5
1  andaman-&-nicobar-islands  2019        2                     9
2  andaman-&-nicobar-islands  2019        3                    22
3  andaman-&-nicobar-islands  2019        4                    34
4  andaman-&-nicobar-islands  2020        1                    55

In [45]:
merchants_df.shape

(1178, 4)

In [46]:
transactions_wide = transactions_df.pivot_table(
    index=["state", "year", "quarter"],
    columns="category",
    values=["count", "amount"]
).reset_index()

transactions_wide.head()

                              state  year quarter        amount                \
category                                                    P2P        Retail
0         andaman-&-nicobar-islands  2018       1  1.551346e+07  1.848410e+06
1         andaman-&-nicobar-islands  2018       2  3.074418e+07  3.511613e+06
2         andaman-&-nicobar-islands  2018       3  5.972496e+07  4.636739e+06
3         andaman-&-nicobar-islands  2018       4  9.689926e+07  7.469343e+06
4         andaman-&-nicobar-islands  2019       1  1.133227e+08  8.596449e+06

                          count
category       Utility      P2P   Retail Utility
0         1.207260e+06   2297.0   6656.0   136.0
1         1.261486e+06   4383.0  10462.0   217.0
2         2.981727e+06   7608.0  13138.0   408.0
3         3.614453e+06  12260.0  18359.0   520.0
4         4.433623e+06  15423.0  24638.0   665.0

In [47]:
transactions_wide.columns = [
    "state", "year", "quarter",
    "p2p_amount", "retail_amount", "utility_amount",
    "p2p_count", "retail_count", "utility_count"
]

transactions_wide.head()

,state,year,quarter,p2p_amount,retail_amount,utility_amount,p2p_count,retail_count,utility_count
0,andaman-&-nicobar-islands,2018,1,1.551346e+07,1.848410e+06,1.207260e+06,2297.0,6656.0,136.0
1,andaman-&-nicobar-islands,2018,2,3.074418e+07,3.511613e+06,1.261486e+06,4383.0,10462.0,217.0
2,andaman-&-nicobar-islands,2018,3,5.972496e+07,4.636739e+06,2.981727e+06,7608.0,13138.0,408.0
3,andaman-&-nicobar-islands,2018,4,9.689926e+07,7.469343e+06,3.614453e+06,12260.0,18359.0,520.0
4,andaman-&-nicobar-islands,2019,1,1.133227e+08,8.596449e+06,4.433623e+06,15423.0,24638.0,665.0

In [48]:
master_df = transactions_wide.merge(
    users_df,
    on=["state", "year", "quarter"],
    how="left"
)

master_df = master_df.merge(
    merchants_df,
    on=["state", "year", "quarter"],
    how="left"
)

master_df.head()

,state,year,quarter,p2p_amount,retail_amount,utility_amount,p2p_count,retail_count,utility_count,registered_users,registered_merchants
0,andaman-&-nicobar-islands,2018,1,1.551346e+07,1.848410e+06,1.207260e+06,2297.0,6656.0,136.0,9292,NaN
1,andaman-&-nicobar-islands,2018,2,3.074418e+07,3.511613e+06,1.261486e+06,4383.0,10462.0,217.0,12739,NaN
2,andaman-&-nicobar-islands,2018,3,5.972496e+07,4.636739e+06,2.981727e+06,7608.0,13138.0,408.0,15949,NaN
3,andaman-&-nicobar-islands,2018,4,9.689926e+07,7.469343e+06,3.614453e+06,12260.0,18359.0,520.0,20050,NaN
4,andaman-&-nicobar-islands,2019,1,1.133227e+08,8.596449e+06,4.433623e+06,15423.0,24638.0,665.0,24369,5.0

In [49]:
master_df.shape

(1224, 11)

In [50]:
master_df.isnull().sum()

state                    0
year                     0
quarter                  0
p2p_amount               0
retail_amount            0
utility_amount           1
p2p_count                0
retail_count             0
utility_count            1
registered_users         0
registered_merchants    46
dtype: int64

In [51]:
master_df.to_csv("pulse_master_data.csv", index=False)